# Используем базовый образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости (включая react-scripts)
RUN npm install --frozen-lockfile

# Копируем остальные файлы проекта
COPY . .

# Указываем порт (опционально)
ENV PORT=3000

# Запускаем приложение
CMD ["npm", "start"]