FROM node:18-alpine

WORKDIR /app

# Копируем только package файлы
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы (кроме node_modules)
COPY . .

ENV PORT=3000
CMD ["npm", "start"]