CREATE TABLE logs (
    id SERIAL PRIMARY KEY,
    branch VARCHAR(255) NOT NULL,
    arch VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    version VARCHAR(100) NOT NULL,
    url TEXT NOT NULL,
    updated TIMESTAMP NOT NULL,
    tbfs_since TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cluster (
    id SERIAL PRIMARY KEY,
    log_id INT NOT NULL,
    Ox DOUBLE PRECISION NOT NULL,
    Oy DOUBLE PRECISION NOT NULL,
    Cluster_id INT NOT NULL,
    FOREIGN KEY (log_id) REFERENCES logs(id)
);