apiVersion: 1

datasources:
  - name: Loki
    type: loki
    acess: proxy
    url: http://loki:3100
    editable: true
  
  - name: Prometheus
    type: prometheus
    acess: proxy
    usrl: http://prometheus:9090
    isDefault: true
    editable: true