{
 "title": "ML dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Drift Score",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "drift_score{job=\"drift\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Development Rare Logs",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{container=\"ml_dev\", service_name=\"ml_dev\"}"
    }
   ]
  },
  {
   "title": "Development Logs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({container=\"ml_dev\",service_name=\"ml_dev\"}[$__auto])"
    }
   ]
  },
  {
   "title": "GET total score",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pie Total Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{job=\"drift\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"ml_dev:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Collected Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{job=\"drift\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}